#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include "sorting.h"
#include "normal_data.h"
#include "fileProcessing.h"
namespace py = pybind11;

PYBIND11_MODULE(data_engine, m){
    m.def("quickSort", &quickSort);
    m.def("insertionSort", &insertionSort);
    m.def("bubbleSort", &bubbleSort);
    m.def("sum", &sum);
    m.def("mean", &mean);
    m.def("median", &median);
    m.def("mode", &mode);    
    m.def("var", &var);    
    m.def("min", &mini);    
    m.def("max", &maxi);    
    m.def("range", &range);    
    m.def("zscore", &zscore);    
    m.def("percentile", &percentile);    
    m.def("std_dev", &std_dev);
    m.def("matrixMultiply", &matrixMultiply);
    m.def("matrixAdd", &matrixAdd);
    m.def("matrixSubtract", &matrixSubtract);
    m.def("getLabels", &getLabels);
    m.def("meanWhole", &meanWhole);
    m.def("medianWhole", &medianWhole);
    m.def("modeWhole", &modeWhole);
    m.def("varWhole", &varWhole);
    m.def("miniWhole", &miniWhole);
    m.def("maxiWhole", &maxiWhole);
    m.def("rangeWhole", &rangeWhole);
    m.def("zscoreWhole", &zscoreWhole);
    m.def("percentileWhole", &percentileWhole);
    m.def("std_devWhole", &std_devWhole);
    m.def("insertionSort", &insertionSort);
    m.def("bubbleSort", &bubbleSort);
    m.def("quickSort", &quickSort);
    m.def("fileHandle", &fileHandle);
}
